### ISSUE TITLE
请教一下多账号怎么设置

### ISSUE THREAD

**Issue by KyleLyric** [superHao2000/autoCheck#2]
请教一下各位config.yaml中多账号要怎么设置，我试了#、@、\n都不行，试的雨晨

**Comment by superHao2000** [comment]
```
    -   username: ''
        password: ''
        user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
            like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
    -   username: ''
        password: ''
        user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
              like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
```

**Comment by KyleLyric** [comment]
> ```
>     -   username: ''
>         password: ''
>         user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
>             like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
>     -   username: ''
>         password: ''
>         user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
>               like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
> ```

感谢解答
